import pandas as pd

configfile: "config/config.yaml"

# load sample table
def load_sample_table(sample_table):
    sampleTable = pd.read_csv(sample_table, index_col=0, sep="\t")
    return sampleTable

sample_dt = load_sample_table(os.getcwd() + '/samples.tsv')

# get input     
def get_fqs(wildcards):
    fqs = sample_dt.loc[wildcards.sample, 'fqs']
    return fqs.split(',')

# load sample table
def get_samples(seq_type):
    sample_dt_f = sample_dt.loc[sample_dt['type'] == seq_type]
    return sorted(sample_dt_f.index.values)

rule all:
    input:
        "matrix_illumina.tsv",
        "matrix_nanopore.tsv",

rule illunima:
    input: "matrix_illumina.tsv"

rule nanopore:
    input: "matrix_nanopore.tsv"

include: "rules/illumina.smk"
include: "rules/nanopore.smk"
