from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/snakemake-workflow-template as a module
module snakemake_workflow_template:
    snakefile: 
        github("snakemake-workflows/snakemake-workflow-template", path="workflow/Snakefile", tag="null")
    config:
        config


# use all rules from https://github.com/snakemake-workflows/snakemake-workflow-template
use rule * from snakemake_workflow_template
